[package]
name                    = "subtle-ng-derive"
description             = "Derive macros for subtle-ng traits."
authors                 = ["Danny McClanahan <dmcC2@hypnicjerk.ai>"]
license                 = "BSD-3-Clause"
repository              = "https://github.com/cosmicexplorer/subtle-ng-derive"
version                 = "0.0.0"
edition                 = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro              = true

[dependencies]
proc-macro2             = "1"
quote                   = "1"
syn                     = "1"
